### PR TITLE
Use proper JSON data deserialization

### PR DESCRIPTION
**Pull request by thallgren**
Switch to use the pcore deserializer for JSON as it is capable of
handling all sorts of data, even empty maps.

This fixes the submap problem reported in #47.

### CODE REVIEW

**Comment by hbuckle** [comment]
Seeing a very weird issue with certain values. It seems to be values that are the same but longer than 20 characters are returning `__pref`

```yaml
test:
  one:
    thing: eeeeeeeeeeeeeeeeeeeeee
  two:
    something: eeeeeeeeeeeeeeeeeeeeee
```

```
lookup test --render-as json
{"one":{"thing":"eeeeeeeeeeeeeeeeeeeeee"},"two":{"something":{"__pref":4}}}
```

If I add or remove a single `e` from one of the values it renders correctly

**Comment by thallgren** [comment]
Right. The __pref here is a "pcore reference" to a previously serialized value and since you serialize the exact same value twice, the second is serialized as a reference to the first :-)

I guess that particular option should be turned off here. Will fix...

**Comment by hbuckle** [comment]
Just testing this with our various configurations, looking good so far

**Comment by thallgren** [comment]
@hbuckle do you reckon it's OK to merge this one now or do you have more tests to run?

**Comment by hbuckle** [comment]
It's working with all of the data we've tried, so should be good

**Comment by ahpook** [comment]
@hbuckle go ahead and merge it! be bold 😁

**Pull request merged**
